#!/usr/bin/env bash

FLUTTER_VERSION=3.0.0
FLUTTER_CHANNEL=stable
DART_VERSION=2.17.

echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV
echo "FLUTTER_CHANNEL=$FLUTTER_CHANNEL" >> $GITHUB_ENV
echo "DART_VERSION=$DART_VERSION" >> $GITHUB_ENV