name: setup-env

description: "Sets up the environment"

runs:
  using: "composite"
  steps:
    - name: "Checkout ${{github.repository}}..."
      uses: actions/checkout@v3
    - name: "Load environment variables..."
      run: chmod +x ./md && ./md ./.github/config.sh