name: setup-env

description: "Sets up the environment variables"

runs:
  using: "composite"
  steps:
    - name: "Load environment variables..."
      run: chmod +x ./md && ./md ./.github/config.sh
      shell: bash