name: setup-env

description: "Sets up the environment"

runs:
  using: "composite"
  steps:
    - run: chmod +x ./md && ./md ./.github/config.sh
      shell: bash
    - name: "Download Flutter v${{env.FLUTTER_VERSION}} on channel ${{env.FLUTTER_CHANNEL}}..."
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{env.FLUTTER_VERSION}}
        cache: true
        cache-key: ${{env.FLUTTER_VERSION}}
        channel: ${{env.FLUTTER_CHANNEL}}
