name: setup-flutter

description: "Set up Flutter"

runs:
  using: "composite"
  steps:
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{env.FLUTTER_VERSION}}
        cache: true
        cache-key: ${{env.FLUTTER_VERSION}}
        channel: ${{env.FLUTTER_CHANNEL}}