name: setup-flutter

description: "Sets up Flutter"

runs:
  using: "composite"
  steps:
    - name: "Download Flutter v${{env.FLUTTER_VERSION}} on channel ${{env.FLUTTER_CHANNEL}}..."
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{env.FLUTTER_VERSION}}
        cache: true
        cache-key: ${{env.FLUTTER_VERSION}}
        channel: ${{env.FLUTTER_CHANNEL}}