name: setup-flutter

on:
  workflow_call:

jobs:
  setup-flutter:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{github.repository}}..."
        uses: actions/checkout@v3
      - name: "Load environment variables..."
        run: chmod +x ./md && ./md ./.github/config.sh
      - name: "Download Flutter v${{env.FLUTTER_VERSION}} on channel ${{env.FLUTTER_CHANNEL}}..."
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          cache: true
          cache-key: ${{env.FLUTTER_VERSION}}
          channel: ${{env.FLUTTER_CHANNEL}}